Fix non-existant file error log
Attempting to log file.originalPath caused a ReferenceError because file was not defined, eliminating any helpful message that may have existed.

In addition, having that as log level info could cause the user not to see the error if they have karma logging set to karma.LOG_ERROR.

Previously, the error for an improperly configured emblem path looked like the following, and did not show up with karma.LOG_ERROR:

```
WARN [preprocess]: Can not load "emblem"!
  ReferenceError: file is not defined
    at createEmblemPreprocessor (/Users/kerrick/Developer/node-webkit-tomster-seed/node_modules/karma-emblem-preprocessor/lib/main.js:25:146)
    at Array.invoke [as 0] (/Users/kerrick/Developer/node-webkit-tomster-seed/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at get (/Users/kerrick/Developer/node-webkit-tomster-seed/node_modules/karma/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/kerrick/Developer/node-webkit-tomster-seed/node_modules/karma/lib/preprocessor.js:40:37)
    at Array.forEach (native)
    at /Users/kerrick/Developer/node-webkit-tomster-seed/node_modules/karma/lib/preprocessor.js:57:29
    at /Users/kerrick/Developer/node-webkit-tomster-seed/node_modules/karma/lib/file-list.js:196:17
    at Object.oncomplete (fs.js:107:15)
```

Now, the error for an improperly configured emblem path looks like the following, and shows up with karma.LOG_ERROR:

```
ERROR [preprocessor.emblem]: karmaEmblemPreprocessor couldn't load dependencies for Emblem.
 ENOENT, no such file or directory 'bower_components/emblem/emblem.js'
 Compiling emblem templates won't work
```